version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: imoodly_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - imoodly_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: imoodly_backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env.development.docker
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    networks:
      - imoodly_network

volumes:
  pgdata:

networks:
  imoodly_network:
