version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: imoodly_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - '5433:5432'
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    networks:
      - imoodly_network

  backend:
    build: .
    container_name: imoodly_backend_test
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env.test
    ports:
      - '3001:3001'
    command: npm run start:test
    networks:
      - imoodly_network

volumes:
  pgdata_test:

networks:
  imoodly_network:
