version: '3.9'

services:
  backend:
    build: .
    dns:
      - 8.8.8.8
    container_name: imoodly_backend_prod
    restart: always
    env_file:
      - .env.production
    ports:
      - '3001:3001'
    command: npm run start:prod
    networks:
      - imoodly_network

networks:
  imoodly_network:
